### PR TITLE
Add ChibiRex & Yeti demos.

### PR DESCRIPTION
**Pull request by Jaskar**

### CODE REVIEW

**Comment by deltakosh** [comment]
Excellent!!! Can you add UI (GUI) to control the quantity of particles 
Also it could be cool to rely more on particles sheet to have various flakes

**Comment by deltakosh** [comment]
Can you also use createEnvironment to get a ground like here:
https://www.babylonjs-playground.com/#10D6YT#56

**Comment by Jaskar** [comment]
Done! :)

**Comment by deltakosh** [comment]
I don't see it :( Still no ground

**Comment by Jaskar** [comment]
My bad @deltakosh 
New commit comming !!!

**Comment by deltakosh** [comment]
Fo yeti, can you make sure that flakes do not change after emitted. We just want different flakes at start
Also updateSpeed value range has to be reduced from (0 to 0.02 max)
Also the flakes should disappears when reaching the ground (lifetime has to be reduced)

**Comment by deltakosh** [comment]
Last one: increase minZ on the helmet to avoid entering inside it :)

**Comment by Jaskar** [comment]
Here you go sir!

**Comment by deltakosh** [comment]
Perfect!

**Pull request merged**
