### PR TITLE
adding link to my tutorial

### PR DESCRIPTION
**Pull request by Vinc3r**
as suggested by Deltakosh, kind-of proud to be on the BJS welcome page :)

### CODE REVIEW

**Comment by deltakosh** [comment]
This is great

**Comment by Vinc3r** [comment]
Just to satisfy my enthusiasm, sorry :-D When will the site be updated ?

**Comment by deltakosh** [comment]
Now :)

**Comment by Vinc3r** [comment]
yeah, mega-class, thanks! :)

**Pull request merged**
