### PR TITLE
Adding Gallery Item

### PR DESCRIPTION
**Pull request by Pryme8**
Procedural Lamp - Gallery Item.

### CODE REVIEW

**Comment by deltakosh** [comment]
Need the image as well :)

**Comment by Pryme8** [comment]
I think that should be it.

**Comment by deltakosh** [comment]
Sorry :) need the picture to be 800x500

**Comment by Pryme8** [comment]
I will fix now ^_^, sorry did not know the dimensions.

**Comment by deltakosh** [comment]
Wonderful thanks!

**Comment by Pryme8** [comment]
I don't know photoshop at work so that was a pain hahaha!

**Pull request merged**
