### PR TITLE
playground demo support on the website

### PR DESCRIPTION
**Pull request by RaananW**
The website carousel now supports playground demos.

Changes:

* set `playgroundCode` in config to have a new playground demo
* when in (or hovering above) the playground, carousel will not auto-change until out of the demo
* Added "title" to carousel links so mouse hover will show what's there
* Mobile friendly (with a few hacks to support iframe focus and blur)
* Set 3 (random!) playground links

Please **change the demo codes before deploying** :-)

Note that to make the demo "zoomable", the demo needs to have `noPreventDefault` set to false when using `camera.attachControl`. Otherwise the user will simply scroll through the demo when trying to zoom.

### CODE REVIEW

**Comment by deltakosh** [comment]
Do you mind deploying to a random netlify place so we can see it ? (mostly for @PirateJC  and @PatrickRyanMS )
Thanks a ton (LGTM btw)

**Comment by RaananW** [comment]
Of course, there it is:

https://5e1f5207ef244a5e6ae5a4f8--xenodochial-meninsky-7598bf.netlify.com/

**Comment by RaananW** [comment]
Or better - https://xenodochial-meninsky-7598bf.netlify.com/

**Comment by deltakosh** [comment]
Clsoing for now

**Pull request closed without merging**
